export const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  ADD_PRODUCTS_TO_CART: "ADD_PRODUCTS_TO_CART",
  SET_SHIPPING_INFO_DATA:"SET_SHIPPING_INFO_DATA",
  SET_SHIPPING_METHOD:"SET_SHIPPING_METHOD",
  SET_PAYMENT_INFORMATION:"SET_PAYMENT_INFORMATION"
  
};
